"""Firestore read/write for the training-tracker app.

All sessions live in one collection: "sessions". Doc IDs are
auto-generated by Firestore (no more {date}_{slot} composite keys).
Every doc has a `user_id` field so we can filter to one user's data.

Date-range filtering is done in Python (not in the Firestore query)
to avoid needing a composite index on (user_id, started_at). Fine
for personal-volume datasets.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from functools import lru_cache

import firebase_admin
from firebase_admin import credentials, firestore
from google.cloud.firestore_v1.base_query import FieldFilter

from models import RecoveryLog, Session

log = logging.getLogger("strain.db")

SESSIONS_COLLECTION = "sessions"
RECOVERY_COLLECTION = "recovery_logs"


@lru_cache(maxsize=1)
def _client():
    """Initialize Firestore once and cache the client."""
    if not firebase_admin._apps:
        cred_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
        if cred_path:
            firebase_admin.initialize_app(credentials.Certificate(cred_path))
        else:
            firebase_admin.initialize_app()
    return firestore.client()


def save_session(session: Session) -> Session:
    """Upsert a Session.

    - New session (session.id is None): Firestore generates an ID; the
      saved Session is returned with `id` populated.
    - Existing session (session.id is set): overwrites the doc in place.
      Returns the same Session unchanged.
    """
    if session.id is None:
        doc_ref = _client().collection(SESSIONS_COLLECTION).document()  # auto-gen ID
        session = session.model_copy(update={"id": doc_ref.id})
        log.debug("db.save_session create id=%s user=%s", session.id, session.user_id)
    else:
        doc_ref = _client().collection(SESSIONS_COLLECTION).document(session.id)
        log.debug("db.save_session update id=%s user=%s", session.id, session.user_id)
    doc_ref.set(session.model_dump(mode="json"))
    return session


def get_session(session_id: str) -> Session | None:
    """Fetch one session by ID. Returns None if not found."""
    snap = _client().collection(SESSIONS_COLLECTION).document(session_id).get()
    if not snap.exists:
        return None
    return Session(**snap.to_dict())


def delete_session(session_id: str) -> None:
    """Delete a session by ID. Idempotent — no-op if not found."""
    _client().collection(SESSIONS_COLLECTION).document(session_id).delete()
    log.debug("db.delete_session id=%s", session_id)


def list_all_sessions() -> list[Session]:
    """Every session across ALL users. Admin-only — bypasses the per-user
    ownership filter, so never call this from a user-facing path. Fine at
    personal/beta volume; would need pagination at scale."""
    return [
        Session(**doc.to_dict())
        for doc in _client().collection(SESSIONS_COLLECTION).stream()
    ]


def list_sessions(user_id: str, start: datetime, end: datetime) -> list[Session]:
    """All sessions for `user_id` with `start <= started_at <= end`,
    sorted by started_at ascending.

    Date range is filtered in Python after pulling all user's sessions,
    so we don't need a composite index. Reasonable for personal-volume
    data; would need rethinking at scale.
    """
    query = (
        _client()
        .collection(SESSIONS_COLLECTION)
        .where(filter=FieldFilter("user_id", "==", user_id))
    )
    sessions = [Session(**doc.to_dict()) for doc in query.stream()]
    sessions.sort(key=lambda s: s.started_at)
    return [s for s in sessions if start <= s.started_at <= end]


# ---------------------------------------------------------------------
# Recovery logs — same storage pattern as sessions, separate collection.
# ---------------------------------------------------------------------

def save_recovery(recovery: RecoveryLog) -> RecoveryLog:
    """Upsert a RecoveryLog. Mirrors save_session: new logs (id=None) get a
    Firestore-generated ID returned on the copy; existing logs overwrite."""
    if recovery.id is None:
        doc_ref = _client().collection(RECOVERY_COLLECTION).document()  # auto-gen ID
        recovery = recovery.model_copy(update={"id": doc_ref.id})
        log.debug("db.save_recovery create id=%s user=%s", recovery.id, recovery.user_id)
    else:
        doc_ref = _client().collection(RECOVERY_COLLECTION).document(recovery.id)
        log.debug("db.save_recovery update id=%s user=%s", recovery.id, recovery.user_id)
    doc_ref.set(recovery.model_dump(mode="json"))
    return recovery


def get_recovery(recovery_id: str) -> RecoveryLog | None:
    """Fetch one recovery log by ID. Returns None if not found."""
    snap = _client().collection(RECOVERY_COLLECTION).document(recovery_id).get()
    if not snap.exists:
        return None
    return RecoveryLog(**snap.to_dict())


def delete_recovery(recovery_id: str) -> None:
    """Delete a recovery log by ID. Idempotent — no-op if not found."""
    _client().collection(RECOVERY_COLLECTION).document(recovery_id).delete()
    log.debug("db.delete_recovery id=%s", recovery_id)


def list_all_recovery() -> list[RecoveryLog]:
    """Every recovery log across ALL users. Admin-only (see list_all_sessions)."""
    return [
        RecoveryLog(**doc.to_dict())
        for doc in _client().collection(RECOVERY_COLLECTION).stream()
    ]


def list_recovery(user_id: str, start: datetime, end: datetime) -> list[RecoveryLog]:
    """All recovery logs for `user_id` with `start <= logged_at <= end`,
    sorted by logged_at ascending. Date range filtered in Python (same
    rationale as list_sessions — no composite index needed)."""
    query = (
        _client()
        .collection(RECOVERY_COLLECTION)
        .where(filter=FieldFilter("user_id", "==", user_id))
    )
    logs = [RecoveryLog(**doc.to_dict()) for doc in query.stream()]
    logs.sort(key=lambda r: r.logged_at)
    return [r for r in logs if start <= r.logged_at <= end]
