"""Firestore read/write for the training-tracker app.

All sessions live in one collection: "sessions". Doc IDs are
auto-generated by Firestore (no more {date}_{slot} composite keys).
Every doc has a `user_id` field so we can filter to one user's data.

Date-range filtering is done in Python (not in the Firestore query)
to avoid needing a composite index on (user_id, started_at). Fine
for personal-volume datasets.
"""

from __future__ import annotations

import os
from datetime import datetime
from functools import lru_cache

import firebase_admin
from firebase_admin import credentials, firestore
from google.cloud.firestore_v1.base_query import FieldFilter

from models import Session

SESSIONS_COLLECTION = "sessions"


@lru_cache(maxsize=1)
def _client():
    """Initialize Firestore once and cache the client."""
    if not firebase_admin._apps:
        cred_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
        if cred_path:
            firebase_admin.initialize_app(credentials.Certificate(cred_path))
        else:
            firebase_admin.initialize_app()
    return firestore.client()


def save_session(session: Session) -> Session:
    """Upsert a Session.

    - New session (session.id is None): Firestore generates an ID; the
      saved Session is returned with `id` populated.
    - Existing session (session.id is set): overwrites the doc in place.
      Returns the same Session unchanged.
    """
    if session.id is None:
        doc_ref = _client().collection(SESSIONS_COLLECTION).document()  # auto-gen ID
        session = session.model_copy(update={"id": doc_ref.id})
    else:
        doc_ref = _client().collection(SESSIONS_COLLECTION).document(session.id)
    doc_ref.set(session.model_dump(mode="json"))
    return session


def get_session(session_id: str) -> Session | None:
    """Fetch one session by ID. Returns None if not found."""
    snap = _client().collection(SESSIONS_COLLECTION).document(session_id).get()
    if not snap.exists:
        return None
    return Session(**snap.to_dict())


def delete_session(session_id: str) -> None:
    """Delete a session by ID. Idempotent — no-op if not found."""
    _client().collection(SESSIONS_COLLECTION).document(session_id).delete()


def list_sessions(user_id: str, start: datetime, end: datetime) -> list[Session]:
    """All sessions for `user_id` with `start <= started_at <= end`,
    sorted by started_at ascending.

    Date range is filtered in Python after pulling all user's sessions,
    so we don't need a composite index. Reasonable for personal-volume
    data; would need rethinking at scale.
    """
    query = (
        _client()
        .collection(SESSIONS_COLLECTION)
        .where(filter=FieldFilter("user_id", "==", user_id))
    )
    sessions = [Session(**doc.to_dict()) for doc in query.stream()]
    sessions.sort(key=lambda s: s.started_at)
    return [s for s in sessions if start <= s.started_at <= end]
